### ISSUE TITLE
Proposal: Move the xcp-ng IRC channel to oftc.net

### ISSUE THREAD

**Issue by gwd** [xcp-ng/xcp-ng-org#103]
This message is because the xcp-ng project is listed as having IRC channels on `freenode.net` (see https://xenproject.org/help/irc/ )

There's been a situation developing on freenode for some time that came to a head last week.  Since that time, the new operators of freenode have begun seizing control of any channel whose topic mentions moving to a new server.  Furthermore, they have been using the number of people logged into freenode as evidence that the community supports their actions.

In response to this, the main hypervisor project has decided to move to `oftc.net` effective immediately, and a number of us have deleted our freenode accounts ( https://lists.xenproject.org/archives/html/xen-devel/2021-05/msg01057.html ).

If you're still using the IRC channel listed in that page, please consider following suit.  If you're not using the IRC channel, let me know so I can delete references to it.

**Comment by olivierlambert** [comment]
FYI, we'll move to `oftc.net` ASAP to stay on the same network than Xen Project.

**Comment by gwd** [comment]
Great, thanks -- I'll update the webpage.

**Comment by olivierlambert** [comment]
Channels created, now we'll make an announcement soon on Freenode channels to tell people to migrate

**Comment by gwd** [comment]
Thanks @olivierlambert !
