### ISSUE TITLE
Minimum required size for USB key for installation ISO

### ISSUE THREAD

**Issue by erhhung** [xcp-ng/xcp-ng-org#17]
Trying to follow the installation guide to create an installation media using a USB key, but don't know what size I need.
It would be nice if the install docs mentioned the minimum required size.
The ISO itself is well under 1GB, but I suspect the installer will be much larger.

**Comment by olivierlambert** [comment]
Because it's an ISO (that you can transfer on an USB key by using `dd`), the space used on the USB medium isn't larger than the ISO size.

Or maybe I didn't get your question?

**Comment by erhhung** [comment]
Yeah, I figured that out. However, I wouldn't say it's basic knowledge that ISO size is the same as on the medium (like file size vs size on disk). I just recommend, especially for the Windows users that don't normally use `dd`, to add a sentence in the install docs that say a 1GB or larger USB medium will work.

**Comment by olivierlambert** [comment]
Oh okay. Makes sense. Would you mind to make the proper formulation in the doc yourself via a pull request here, so next time other people will get a more precise idea?
