### ISSUE TITLE
Avoid one extra reboot after a fresh install

### ISSUE THREAD

**Issue by AtaxyaNetwork** [xcp-ng/xcp-ng-org#196]
Right now, when an install is just finished, you need to reboot. And after that, one the host is added in XO(A), you need to update, and finally reboot again. Which is fine in most case, but sometimes your hardware is taking almost 10 minutes to reboot, it could be a unreasonable loss of time.

Is there a way to avoid this? Could we install updates directly in the install chroot? Or to have automation? Or maybe to enable "install updates" in the installer like in Ubuntu for example?

Thanks in advance for your suggestion :)

**Comment by stormi** [comment]
There's no way to do it currently. One may try to do it from a custom script running at the end of the installation (https://github.com/xcp-ng/host-installer/blob/master/doc/answerfile.txt#L104) but I can't guarantee that all RPMs are able to update correctly without the host being running (an update doesn't trigger the same scripts as an initial installation).

There is an enhancement request at https://github.com/xcp-ng/xcp/issues/353
