### ISSUE TITLE
Installer Software Raid fails when existing mdraid volumes exist

### ISSUE THREAD

**Issue by mikebutash** [xcp-ng/xcp-ng-org#219]
Trying to check out xcp-ng today from an old system with existing mdraid volumes, using the software raid setup for system disk selection simply does not work and errors out.  I had several setup on different disks I was tossing in my frankenstein lab box, and annoyingly needed to remove all other ancillary disks physically, and booting into another os to secure-erase the existing nvme disks to before the software raid function actually worked.

Even more annoying, it didn't really error or anything, it simply never made a new raid volume, only listing the old raid volume it already discovered.  Really ought to fix this lest this be a barrier to entry for being simply dumb from the start of the experience.

**Comment by olivierlambert** [comment]
Hi,

This is not the right place to open the issue. https://github.com/xcp-ng/xcp is recommended, or even asking on the community forum: https://xcp-ng.org/forum
