### ISSUE TITLE
Documentation incorrectly stating xe-guest-utilities not being packages in Ubuntu anymore

### ISSUE THREAD

**Issue by XSpielinbox** [xcp-ng/xcp-ng-org#238]
At https://github.com/xcp-ng/xcp-ng-org/blob/master/docs/guests.md#ubuntu it is written that the `xe-guest-utilities` have not been packaged since Ubuntu 20.04. This is not true anymore. They are available in Ubuntu 22.04 and newer versions. I have checked that on my own VMs. A good overview is also provided at [repology.org](https://repology.org/project/xe-guest-utilities/versions).
I am unsure how it has been for Ubuntu 20.10 to 21.10 - as these are not supported anymore, I would say, that it would not matter if they haven't been available in these releases.

**Comment by stormi** [comment]
Thanks for the notice. I see it's in `universe` now, not in `main` anymore. Does this mean you need to enable repositories before installing? (in which case the installation instructions also need updating).

**Comment by stormi** [comment]
Solved in https://github.com/xcp-ng/xcp-ng-org/pull/239. Thank you.
