### ISSUE TITLE
Docs page missing info for XO lite

### ISSUE THREAD

**Issue by adamwbb** [xcp-ng/xcp-ng-org#267]
The XO Lite page https://docs.xcp-ng.org/management/manage-locally/xo-lite/
infers that XO lite is already built in and dos not have any setup.
This is misleading and having to huntdown instrucitons from forums. Please add the steps to install XO Lite on the xcp-ng server.

**Comment by olivierlambert** [comment]
Hi,

For XCP-ng 8.3, it is perfectly true: it is bundled by default without any extra instruction needed to set it up.

It's possible it will never be included by default on 8.2, so I updated the page showing about XO Lite is meant for 8.3, and could be used on 8.2 while using an external URL.
