### ISSUE TITLE
Suggest removal of xcp-ng.org/docs/

### ISSUE THREAD

**Issue by keyboardslap** [xcp-ng/xcp-ng-org#291]
Content on docs.xcp-ng.org does not match content on xcp-ng.org/docs/. This is because changes to the `docs` directory in this repo are only reflected on docs.xcp-ng.org. Unfortunately, search engines like Google still present (out-of-date) results from xcp-ng.org/docs/. Example:

![image](https://github.com/user-attachments/assets/0c467310-f544-4a6a-90bf-e67520b45b1a)

Some requests to xcp-ng.org/docs/* are automatically redirected to docs.xcp-ng.org/*, but not all. Example: [https://xcp-ng.org/docs/install.html](https://xcp-ng.org/docs/install.html) redirects to [https://docs.xcp-ng.org/installation/install-xcp-ng/](https://docs.xcp-ng.org/installation/install-xcp-ng/), but [https://xcp-ng.org/docs/migratetoxcpng.html](https://xcp-ng.org/docs/migratetoxcpng.html) does NOT redirect to [https://docs.xcp-ng.org/installation/migrate-to-xcp-ng/](https://docs.xcp-ng.org/installation/migrate-to-xcp-ng/). 

I suggest that these missing redirects are put in place, and the content at xcp-ng.org/docs/ removed, so users are not directed to out-of-date information.

**Comment by olivierlambert** [comment]
Hi,

We are moving progressively, I'll add the missing redirect. Also, xcp-ng.org/docs itself is redirecting to the new doc.

**Comment by keyboardslap** [comment]
Using the query `site:xcp-ng.org/docs/` on Google, I was able to find these pages that don't have redirects:

- https://xcp-ng.org/docs/guests.html
- https://xcp-ng.org/docs/networking.html
- https://xcp-ng.org/docs/architecture.html
- https://xcp-ng.org/docs/roadmap.html
- https://xcp-ng.org/docs/develprocess.html
- https://xcp-ng.org/docs/ha.html
- https://xcp-ng.org/docs/backup.html
- https://xcp-ng.org/docs/storage.html
- https://xcp-ng.org/docs/cloud.html
- https://xcp-ng.org/docs/ecosystem.html
- https://xcp-ng.org/docs/answerfile.html
- https://xcp-ng.org/docs/security.html
- https://xcp-ng.org/docs/guides.html
- https://xcp-ng.org/docs/gitrepo.html
- https://xcp-ng.org/docs/api.html
- https://xcp-ng.org/docs/project.html
- https://xcp-ng.org/docs/licenses.html
- https://xcp-ng.org/docs/hosting.html
- https://xcp-ng.org/docs/release-8-1.html

No rush! Thanks for the fixes so far.

**Comment by nathanael-h** [comment]
Hello @olivierlambert can you give me some context so that I can add missing redirections correctly?

**Comment by nathanael-h** [comment]
I added missing redirections rules. Thanks for the report @keyboardslap !
