### ISSUE TITLE
Don't use admin secret on ceph SR

### ISSUE THREAD

**Issue by hoerup** [xcp-ng/xcp-ng-org#37]
The ceph section in https://github.com/xcp-ng/xcp-ng-org/blob/master/docs/storage.md a admin user is used for accessing ceph. 

It should be noted that this is NOT best practice for accessing cephfs and that in production a new keyring should be used with only the necessary privs

**Comment by stormi** [comment]
Thanks for the advice. Could you use the link at the bottom of the documentation page to contribute the change?

**Comment by hoerup** [comment]
Added a note in #43

**Comment by stormi** [comment]
Thanks! Closing since your PR will be merged very soon.
