### ISSUE TITLE
Exposed .git on webpage

### ISSUE THREAD

**Issue by userbradley** [xcp-ng/xcp-ng-org#9]
Hi,

Not sure how much of an issue this can be but there is an exposed .git folder on the website. Despite being access denied (403) I was able to still see /HEAD as well as /refs/heads/master

once again, not sure if this is an issue or not. Thought I would still bring it up

**Comment by stormi** [comment]
Thanks for the report. Pinging @olivierlambert

**Comment by olivierlambert** [comment]
Fixed.
