### ISSUE TITLE
Migration from Xen project to XCP-ng

### ISSUE THREAD

**Issue by MushyMiddle** [xcp-ng/xcp-ng-org#90]
Hi.  Missing from https://github.com/xcp-ng/xcp-ng-org/edit/master/docs/migratetoxcpng.md (https://xcp-ng.org/docs/migratetoxcpng.html) is any information on how one might either migrate from Xen project (i.e. non-Citrix Xen) to XCP-ng, or add XCP-ng to an existing Xen project host, if that's even feasible.  I'm assuming that I'd have to just do a clean install, but what about my existing VM disks (LVs), e.g.?  I guess I can just dd them off to my NAS, but will I be able to recover them on XCP-ng?  Etc.

Some of my confusion might stem from the Xen-that-isn't-Citrix terminology problem.

In my case, Xen is running on Ubuntu, so my guess is that I'm in for a complete rebuild; but happy to be proven wrong.

**Comment by olivierlambert** [comment]
Here is an old (but still accurate) help on that: https://xen-orchestra.com/blog/migrate-from-xen-to-xenserver/

And you are right, we'll add it into the documentation soon, it's missing right now :+1:

**Comment by olivierlambert** [comment]
Done: https://xcp-ng.org/docs/migratetoxcpng.html#from-xen-on-linux
