### ISSUE TITLE
CLI Reference Docs help command - XCP-ng 8.2

### ISSUE THREAD

**Issue by cmd-not-found** [xcp-ng/xcp-ng-org#91]
## Description

When following the guide on the `xe` CLI, the first command example `xe help command` fails.

## Details

When following the guide here:

> <https://xcp-ng.org/docs/cli_reference.html>

The first command presented `xe help command` fails. 

```
[20:29 oasis ~]# xe help command
Unknown command 'command'
[20:29 oasis ~]# xe help
Usage: xe <command> [-s server] [-pw passwd] [-p port] [-u user] [-pwf password-file]
  [command specific arguments]

To get help on a specific command: xe help <command>
To get a full listing of commands: xe help --all

Common command list
-------------------
    cd-list, diagnostic-vm-status, network-list, snapshot-clone
    snapshot-copy, snapshot-disk-list, snapshot-export-to-template
    snapshot-reset-powerstate, snapshot-revert, snapshot-uninstall, sr-list
    template-export, template-uninstall, vm-cd-add, vm-cd-eject
    vm-cd-insert, vm-cd-list, vm-cd-remove, vm-checkpoint, vm-clone
    vm-compute-maximum-memory, vm-copy, vm-disk-add, vm-disk-list
    vm-disk-remove, vm-export, vm-import, vm-install, vm-list, vm-migrate
    vm-pause, vm-reboot, vm-reset-powerstate, vm-resume, vm-shutdown
    vm-snapshot, vm-snapshot-with-quiesce, vm-start, vm-suspend
    vm-uninstall, vm-unpause, vm-vif-list
[20:29 oasis ~]# xe help command
```

## Other Notes

Maybe I'm over-analyzing the docs and `command` is supposed to be a generic stand-in. If so, it might be more helpful to lead with the `xe help` command and then add `<>` around the boilerplate examples that don't actually work. Happy to submit a PR to propose better clarity if this is just a mis-reading of the docs and not an actual missing `command`.

**Comment by olivierlambert** [comment]
"Command" is given by the "Common command list" in the output you provided.

Eg: xe help cd-list``

**Comment by cmd-not-found** [comment]
Got ya. I guess my point is that this page is an overview of the `xe` cli, and the very first example `xe help command` must be interpreted by the reader rather than executed outright. I'm new to XCP-ng, so it took me a few minutes to understand the docs and realize I wasn't doing something incorrectly. Trying to save others time is all. This can be closed.

**Comment by olivierlambert** [comment]
You are right: if it's not clear to you, then it will not clear for others :) Can you submit a change to make it more clear?
